name: WakaTime Stats Update
on:
  schedule:
    - cron: "0 0 * * *" # 每天UTC 0点更新
  workflow_dispatch: # 添加手动触发选项

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          DEBUG_LOGGING: "true" # 开启调试模式
