name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # 每天更新一次
  workflow_dispatch: # 保留手动触发功能

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: WakaTime Readme
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Update WakaTime stats in README
        uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          BLOCKS: ⣿⣿⣶⣵⣿⣿⣶⣵
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
          CODE_LANG: txt
