name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *" # 每小时更新一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update WakaTime stats in README
        uses: athul/waka-readme@v0.2.2
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 必须是你生成的 PAT（具备 repo 和 read:user 权限）
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: true
          SHOW_COMMIT: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LOC_CHART: true
          DEBUG_LOGGING: true  # 正确的调试参数
