name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main  # 指定分支

      - name: Clear README Cache
        run: git rm --cached README.md

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        env:
          ACTIONS_STEP_DEBUG: true  # 调试模式
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          CODE_LANG: txt
