name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # 每两小时运行一次
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: 更新此仓库的 README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          COMMIT_MESSAGE: "chore: 更新 WakaTime 统计数据"
          BLOCKS: "░▒▓"